services:
  cs2-medal-parser:
    # use prebuilt image from docker hub
    image: tomjm69/cs-medal-parser:latest
    # uncomment, to build image locally from git repository
    # build: .
    container_name: cs-medal-parser
    volumes:
      # Persistent data storage for medals and API responses
      - ./data/:/app/data/
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
